(function(){
  'use strict';
  var products=[
    {id:1,sku:'MIG-200A',barcode:'6975421300012',name:'MIG-200A 逆变式气体保护焊机',specification:'200A / 欧规',status:'可售',logistics:'带磁',supplier:'深圳焊虎机电有限公司',price:'¥ 1,280.00',createdAt:'2026-09-18 10:32',icon:'⚡'},
    {id:2,sku:'TIG-ROD-316L',barcode:'6975421300067',name:'TIG 316L 不锈钢氩弧焊丝 1.6mm',specification:'5kg / 1.6mm',status:'可售',logistics:'普货',supplier:'东莞市华诚五金有限公司',price:'¥ 86.50',createdAt:'2026-09-17 14:20',icon:'〰'},
    {id:3,sku:'PLASMA-45',barcode:'6975421300135',name:'CUT-45 等离子切割机 45A',specification:'45A / 美规',status:'开发中',logistics:'带电',supplier:'宁波锐虎机械有限公司',price:'¥ 938.00',createdAt:'2026-09-16 09:15',icon:'✦'},
    {id:4,sku:'WELD-HELMET-01',barcode:'6975421300227',name:'自动变光焊接面罩 Pro',specification:'黑色 / 1件',status:'可售',logistics:'普货',supplier:'深圳焊虎机电有限公司',price:'¥ 198.00',createdAt:'2026-09-12 16:40',icon:'◒'},
    {id:5,sku:'CABLE-35MM',barcode:'6975421300289',name:'35mm² 铜芯焊把线 10米',specification:'10m / 35mm²',status:'停售',logistics:'普货',supplier:'东莞市华诚五金有限公司',price:'¥ 152.00',createdAt:'2026-09-10 11:08',icon:'⌇'},
    {id:6,sku:'GAS-REGULATOR',barcode:'6975421300357',name:'氩气减压器带流量计',specification:'AR-25 / 单表',status:'可售',logistics:'带磁',supplier:'宁波锐虎机械有限公司',price:'¥ 68.00',createdAt:'2026-09-08 15:25',icon:'◉'}
  ];
  var filtered=products.slice(),selected=new Set(),editing=null,expandedId=null;
  var body=document.querySelector('#productTableBody'),count=document.querySelector('#resultCount'),empty=document.querySelector('#emptyState');
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function statusClass(status){return status==='可售'?'sale':status==='停售'?'stop':'dev';}
  function render(){
    count.textContent='共 '+filtered.length+' 条'; empty.hidden=filtered.length>0;
    body.innerHTML=filtered.map(function(row){var main='<tr><td><input class="row-check" data-id="'+row.id+'" type="checkbox" '+(selected.has(row.id)?'checked':'')+'></td><td><div class="product-info"><button class="row-expand" data-action="expand" data-id="'+row.id+'">'+(expandedId===row.id?'−':'+')+'</button><span class="product-thumb">'+row.icon+'</span><span class="product-name">'+escapeHtml(row.name)+'</span></div></td><td><span class="sku-code">'+escapeHtml(row.sku)+'</span></td><td>'+escapeHtml(row.barcode)+'</td><td data-column-cell="specification">'+escapeHtml(row.specification)+'</td><td><span class="status '+statusClass(row.status)+'">'+row.status+'</span></td><td><span class="logistics">'+row.logistics+'</span></td><td data-column-cell="supplier">'+escapeHtml(row.supplier)+'</td><td data-column-cell="price">'+row.price+'</td><td data-column-cell="createdAt">'+row.createdAt+'</td><td><button class="link" data-action="edit" data-id="'+row.id+'">编辑</button><button class="link" data-action="log" data-id="'+row.id+'">日志</button></td></tr>';var detail=expandedId===row.id?'<tr class="expanded-row"><td colspan="11"><div class="sku-detail"><div>产品类目<strong>焊接设备 / 焊接耗材</strong></div><div>包装规格<strong>'+escapeHtml(row.specification)+'</strong></div><div>采购信息<strong>'+escapeHtml(row.supplier)+' · '+row.price+'</strong></div><div>维护信息<strong>Admin · '+row.createdAt+'</strong></div></div></td></tr>':'';return main+detail;}).join('');
    document.querySelector('#selectAll').checked=filtered.length>0&&filtered.every(function(row){return selected.has(row.id);});
    document.querySelector('#selectedCount').textContent='已选 '+selected.size+' 项'; document.querySelector('#batchButton').disabled=!selected.size;
    document.querySelectorAll('[data-column]').forEach(function(input){setColumn(input.dataset.column,input.checked);});
  }
  function setColumn(key,visible){document.querySelectorAll('[data-column-head="'+key+'"],[data-column-cell="'+key+'"]').forEach(function(node){node.hidden=!visible;});}
  function split(v){return v.split(/[\s,，、;；]+/).map(function(x){return x.trim().toLowerCase();}).filter(Boolean);}
  function search(){var terms=split(document.querySelector('#keyword').value),type=document.querySelector('#codeType').value,status=document.querySelector('#productStatus').value,logistics=document.querySelector('#logisticsType').value,supplier=document.querySelector('#supplier').value,start=document.querySelector('#startDate').value,end=document.querySelector('#endDate').value;filtered=products.filter(function(row){var field=type==='sku'?row.sku:type==='barcode'?row.barcode:row.name,date=row.createdAt.slice(0,10);return (!terms.length||terms.some(function(t){return field.toLowerCase().indexOf(t)>-1;}))&&(!status||row.status===status)&&(!logistics||row.logistics===logistics)&&(!supplier||row.supplier===supplier)&&(!start||date>=start)&&(!end||date<=end);});selected.clear();expandedId=null;render();}
  function openModal(row){
    editing=row||null;
    var product=row||{sku:'',barcode:'',name:'',specification:'',status:'可售',logistics:'普货',supplier:'',price:'—',createdAt:'',icon:'◈'};
    var mask=document.createElement('div');
    mask.className='sku-editor-mask';
    mask.innerHTML='<section class="sku-editor" role="dialog" aria-modal="true" aria-label="SKU 信息">'
      +'<header class="sku-editor-head"><div class="editor-product"><span class="editor-thumb">'+product.icon+'</span><div><h1>SKU信息 <b>'+ (product.sku||'新建 SKU') +'</b></h1><p>'+ (product.name||'请完善产品基础信息') +'</p></div></div><button class="editor-x" type="button" data-editor-close aria-label="关闭">×</button></header>'
      +'<div class="sku-editor-body"><main class="editor-content">'
      +'<section id="basic" class="editor-section"><h2>基本信息</h2><div class="editor-grid"><label><i>*</i>产品类目<input data-field="category" value="焊接设备 / 焊接耗材"></label><label><i>*</i>默认发货仓<input data-field="warehouse" value="东莞采购仓"></label><label class="wide"><i>*</i>SKU标题<input data-field="name" value="'+escapeHtml(product.name)+'"></label><label><i>*</i>自定义SKU<input data-field="sku" value="'+escapeHtml(product.sku)+'"></label><label>规格<input data-field="specification" value="'+escapeHtml(product.specification)+'"></label><label>型号<input data-field="model" value="'+escapeHtml(product.sku)+'"></label><label><i>*</i>产品状态<select data-field="status"><option '+(product.status==='可售'?'selected':'')+'>可售</option><option '+(product.status==='停售'?'selected':'')+'>停售</option><option '+(product.status==='开发中'?'selected':'')+'>开发中</option></select></label><label>销售状态<select><option>海外仓新品</option><option>常规销售</option><option>清货</option></select></label><label>条码<input data-field="barcode" value="'+escapeHtml(product.barcode)+'"></label></div></section>'
      +'<section id="size" class="editor-section"><h2>尺寸重量</h2><div class="editor-grid"><label>产品长宽高(mm)<input value="320 × 180 × 260"></label><label>产品净重(g)<input value="850"></label><label>包装长宽高(mm)<input value="350 × 210 × 290"></label><label>包装毛重(g)<input value="980"></label></div></section>'
      +'<section id="logistics" class="editor-section"><h2>报关与物流信息</h2><div class="editor-grid"><label>报关品名<input value="'+escapeHtml(product.name)+'"></label><label>海关编码<input value="8515.3900"></label><label><i>*</i>物流属性<select data-field="logistics"><option '+(product.logistics==='普货'?'selected':'')+'>普货</option><option '+(product.logistics==='带电'?'selected':'')+'>带电</option><option '+(product.logistics==='带磁'?'selected':'')+'>带磁</option><option '+(product.logistics==='敏感货'?'selected':'')+'>敏感货</option></select></label><label>申报单价<input value="USD 18.50"></label></div></section>'
      +'<section id="purchase" class="editor-section"><h2>采购信息</h2><div class="editor-grid"><label><i>*</i>供应商<input data-field="supplier" value="'+escapeHtml(product.supplier)+'"></label><label>采购单价<input data-field="price" value="'+escapeHtml(product.price)+'"></label><label>最小起订量<input value="1"></label><label>采购周期(天)<input value="7"></label></div></section>'
      +'<section id="media" class="editor-section"><h2>SKU图片/视频</h2><div class="editor-empty">暂未上传媒体。</div></section><section id="rights" class="editor-section"><h2>侵权/禁售</h2><div class="editor-grid"><label>侵权风险<select><option>正常</option><option>待核查</option><option>侵权</option></select></label><label>禁售状态<select><option>不禁售</option><option>禁售</option></select></label></div></section><section id="copy" class="editor-section"><h2>文案信息</h2><textarea placeholder="请输入产品卖点或描述"></textarea></section><section id="docs" class="editor-section"><h2>产品文档</h2><div class="editor-empty">暂无产品文档</div></section><section id="remarks" class="editor-section"><h2>SKU备注</h2><textarea placeholder="请输入内部备注"></textarea></section>'
      +'</main><aside class="editor-nav" aria-label="信息导航"><button class="active" data-editor-section="basic">基本信息</button><button data-editor-section="size">尺寸重量</button><button data-editor-section="logistics">报关与物流信息</button><button data-editor-section="purchase">采购信息</button><button data-editor-section="media">SKU图片/视频</button><button data-editor-section="rights">侵权/禁售</button><button data-editor-section="copy">文案信息</button><button data-editor-section="docs">产品文档</button><button data-editor-section="remarks">SKU备注</button></aside></div>'
      +'<footer class="sku-editor-foot"><div><button class="button" type="button" data-editor-close>关闭</button><button class="button primary" type="button" data-editor-save>保存</button></div></footer></section>';
    document.body.appendChild(mask);
    mask.addEventListener('click',function(event){
      var close=event.target.closest('[data-editor-close]');
      if(close||event.target===mask){mask.remove();return;}
      var nav=event.target.closest('[data-editor-section]');
      if(nav){mask.querySelectorAll('[data-editor-section]').forEach(function(node){node.classList.remove('active');});nav.classList.add('active');mask.querySelector('#'+nav.dataset.editorSection).scrollIntoView({behavior:'smooth',block:'start'});return;}
      if(event.target.closest('[data-editor-save]')){
        var sku=mask.querySelector('[data-field="sku"]').value.trim(),name=mask.querySelector('[data-field="name"]').value.trim();
        if(!sku||!name){toast('请填写 SKU 和产品名称');return;}
        var data={sku:sku,name:name,barcode:mask.querySelector('[data-field="barcode"]').value.trim()||'—',specification:mask.querySelector('[data-field="specification"]').value.trim()||'—',status:mask.querySelector('[data-field="status"]').value,logistics:mask.querySelector('[data-field="logistics"]').value,supplier:mask.querySelector('[data-field="supplier"]').value.trim()||'—',price:mask.querySelector('[data-field="price"]').value.trim()||'—'};
        if(editing)Object.assign(editing,data);else products.unshift(Object.assign({id:Date.now(),createdAt:new Date().toISOString().slice(0,16).replace('T',' '),icon:'◈'},data));
        filtered=products.slice();mask.remove();render();toast('SKU 产品信息已保存');
      }
    });
  }
  document.querySelector('#searchButton').addEventListener('click',search);document.querySelector('#keyword').addEventListener('keydown',function(e){if(e.key==='Enter')search();});document.querySelector('#resetButton').addEventListener('click',function(){document.querySelector('#keyword').value='';document.querySelector('#codeType').value='sku';document.querySelector('#productStatus').value='';document.querySelector('#logisticsType').value='';document.querySelector('#supplier').value='';document.querySelector('#startDate').value='';document.querySelector('#endDate').value='';filtered=products.slice();selected.clear();render();});
  function toast(text){var node=document.createElement('div');node.className='toast';node.textContent=text;document.body.appendChild(node);window.setTimeout(function(){node.remove();},2200);}
  function openLog(row){
    var logs=[
      {type:'编辑产品信息',content:'更新了规格、物流属性和供应商信息',operator:'Admin',time:'2026-09-20 10:30'},
      {type:'创建产品',content:'新增 SKU 产品档案',operator:'Admin',time:row.createdAt}
    ];
    var mask=document.createElement('div');
    mask.className='purchase-log-modal';
    mask.innerHTML='<div class="purchase-log-dialog" role="dialog" aria-modal="true" aria-label="产品操作日志"><header class="purchase-log-header"><div><h2>操作日志</h2><span>产品 SKU：'+escapeHtml(row.sku)+'</span></div><button class="purchase-log-close" type="button" aria-label="关闭操作日志">×</button></header><div class="purchase-log-body"><table class="purchase-log-table"><thead><tr><th>操作类型</th><th>日志内容</th><th>操作人</th><th>操作时间</th></tr></thead><tbody>'+logs.map(function(log){return '<tr><td>'+log.type+'</td><td class="purchase-log-content">'+log.content+'</td><td>'+log.operator+'</td><td>'+log.time+'</td></tr>';}).join('')+'</tbody></table></div><footer class="purchase-log-footer"><span>共 '+logs.length+' 条</span><div><button class="purchase-log-page" type="button" disabled>‹</button><button class="purchase-log-page active" type="button">1</button><button class="purchase-log-page" type="button" disabled>›</button></div></footer></div>';
    document.body.appendChild(mask);
    mask.addEventListener('click',function(event){if(event.target===mask||event.target.closest('.purchase-log-close'))mask.remove();});
  }
  function openBatch(){var mask=document.createElement('div');mask.className='modal-mask';mask.innerHTML='<section class="modal"><header><h2>批量编辑产品</h2><button class="modal-close" type="button">×</button></header><div class="modal-body"><p class="batch-note">将更新已选择的 '+selected.size+' 个 SKU；留空的字段不修改。</p><div class="form-grid"><label>产品状态<select id="batchStatus"><option value="">不修改</option><option>可售</option><option>停售</option><option>开发中</option></select></label><label>物流属性<select id="batchLogistics"><option value="">不修改</option><option>普货</option><option>带电</option><option>带磁</option><option>敏感货</option></select></label><label class="span-2">供应商<input id="batchSupplier" placeholder="留空则不修改"></label></div></div><footer><button class="button" type="button" data-cancel>取消</button><button class="button primary" type="button" data-save>保存</button></footer></section>';document.body.appendChild(mask);mask.addEventListener('click',function(e){if(e.target===mask||e.target.closest('[data-cancel]')||e.target.closest('.modal-close'))mask.remove();if(e.target.closest('[data-save]')){var status=mask.querySelector('#batchStatus').value,logistics=mask.querySelector('#batchLogistics').value,supplier=mask.querySelector('#batchSupplier').value.trim();products.forEach(function(row){if(selected.has(row.id)){if(status)row.status=status;if(logistics)row.logistics=logistics;if(supplier)row.supplier=supplier;}});mask.remove();toast('已批量更新 '+selected.size+' 个 SKU');render();}});}
  document.querySelector('#selectAll').addEventListener('change',function(e){filtered.forEach(function(row){if(e.target.checked)selected.add(row.id);else selected.delete(row.id);});render();});body.addEventListener('change',function(e){if(!e.target.matches('.row-check'))return;var id=Number(e.target.dataset.id);if(e.target.checked)selected.add(id);else selected.delete(id);render();});body.addEventListener('click',function(e){var button=e.target.closest('[data-action]');if(!button)return;var row=products.find(function(item){return item.id===Number(button.dataset.id);});if(button.dataset.action==='expand'){expandedId=expandedId===row.id?null:row.id;render();}if(button.dataset.action==='edit')openModal(row);if(button.dataset.action==='log')openLog(row);});
  document.querySelector('#addButton').addEventListener('click',function(){openModal();});document.querySelector('#batchButton').addEventListener('click',openBatch);document.querySelector('#importButton').addEventListener('click',function(){toast('导入模板已准备，仅包含 SKU 维度字段。');});document.querySelector('#exportButton').addEventListener('click',function(){toast('已按当前条件导出 '+filtered.length+' 条 SKU 产品。');});
  document.querySelector('#columnButton').addEventListener('click',function(){var panel=document.querySelector('#columnPanel'),show=panel.hidden;panel.hidden=!show;this.setAttribute('aria-expanded',String(show));});document.querySelector('#columnPanel').addEventListener('change',function(e){if(e.target.matches('[data-column]'))setColumn(e.target.dataset.column,e.target.checked);});
  render();
})();
