const suppliers=['JASIC 供应商','ARCCAP 供应商','华南五金','东莞焊材','测试供应商'];
const warehouses=['东莞采购仓','深圳采购仓','宁波采购仓','洛杉矶海外仓','供应商直发仓'];
const platforms=['Amazon','eBay','B2C','线下订单'];
const stores=['ARCCAP','Lowes_ar','arccaptain','Amazon US 旗舰店','线下订单'];
const teams=['亚马逊团队','Jasic团队','eBay团队','B端团队','公共库存'];
const receivers=['张敏','李晨','王磊','赵倩','仓库管理员'];
const creators=['Admin','张敏','李晨','王磊','系统管理员'];
const statusPool=[...Array(7).fill('待提交'),...Array(10).fill('待收货'),...Array(10).fill('已完成')];
const skuPool=['140US260008','42101000004','XX123456-1','DD123456','EE123456','FF123456','KK123456','fan-test-sku'];
const icons=['🎒','🧰','▧','📦','🧯','🪖','🌺','🐹'];

const rows=Array.from({length:27},(_,i)=>({
  id:i+1,ecNo:`ECPO2026${String(805001+i)}`,lxNo:`LXPO2026${String(610001+i)}`,midNo:`PO2026${String(727001+i)}`,
  sku:skuPool[i%skuPool.length],icon:icons[i%icons.length],supplier:suppliers[i%suppliers.length],planNo:`CGJH202608${String(1001+i)}`,batchNo:`PC2026${String(8001+i)}`,
  warehouse:warehouses[i%warehouses.length],platform:platforms[i%platforms.length],store:stores[i%stores.length],team:teams[i%teams.length],receiver:receivers[i%receivers.length],creator:creators[i%creators.length],
  receiveDate:`2026-08-${String(6+(i%22)).padStart(2,'0')}`,status:statusPool[i],amount:`¥ ${(90+i*1376).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`,
  purchaseQty:[9,66,100,2000,110][i%5],transitQty:[0,66,100,2000,110][i%5],arrivedQty:i%4===0?9:i%4===1?0:i%4===2?0:210,pendingQty:i%3===0?0:i%3===1?2000:11,receiveQty:i%4===0?8:0,
  trackingNo:`PO2026${String(805001+i)}`,tax:[0,88,5,0][i%4],materialFee:i%5===0?'¥ 100.00':'¥ 0.00',freight:i%5===0?'¥ 10.00':'¥ 0.00',otherFee:'¥ 0.00'
}));

const statusDefs=[['全部',null],['待提交','待提交'],['待审批','待审批'],['待收货','待收货'],['已完成','已完成']];
const state={suppliers:[],warehouses:[],platforms:[],stores:[],teams:[],receivers:[],creators:['Admin'],status:null,page:1,pageSize:25,selected:new Set(),filtered:[...rows]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(text,type='success'){const el=$('#toast');el.textContent=text;el.classList.toggle('error',type==='error');el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800);}
function closeMenus(except){$$('.multi').forEach(m=>{if(m!==except){m.querySelector('[data-menu]').classList.remove('show');m.querySelector('[data-trigger]').classList.remove('open');}});}
document.addEventListener('click',()=>closeMenus());
function initMulti(rootId,items,key,placeholder){
  const root=$(rootId),trigger=root.querySelector('[data-trigger]'),menu=root.querySelector('[data-menu]');
  const sync=()=>{state[key]=[...menu.querySelectorAll('input:checked')].map(x=>x.value);trigger.textContent=state[key].length?`${state[key].slice(0,2).join('、')}${state[key].length>2?` +${state[key].length-2}`:''}`:placeholder;trigger.classList.toggle('has-value',!!state[key].length);};
  menu.innerHTML=items.map(v=>`<label><input type="checkbox" value="${v}" ${state[key].includes(v)?'checked':''}>${v}</label>`).join('');trigger.onclick=e=>{e.stopPropagation();closeMenus(root);menu.classList.toggle('show');trigger.classList.toggle('open',menu.classList.contains('show'));};menu.onclick=e=>e.stopPropagation();menu.onchange=sync;sync();
}
function splitValues(value){return [...new Set(value.trim().toLowerCase().split(/[\s,，;；]+/).filter(Boolean))];}
function includesAny(value,values){return !values.length||values.some(v=>(value||'').toLowerCase().includes(v));}
function equalsAny(value,values){return !values.length||values.includes(value);}
function validateDates(){const start=$('#startDate').value,end=$('#endDate').value;if((start&&!end)||(!start&&end)){toast('请选择完整的收货时间范围','error');return false;}if(start&&end&&start>end){toast('开始日期不能晚于结束日期','error');return false;}return true;}
function renderTabs(){$('#statusTabs').innerHTML='<span class="tab-check">☑</span>'+statusDefs.map(([label,key])=>`<div class="status-tab ${state.status===key?'active':''}" data-key="${key===null?'__all':key}">${label}(${key===null?rows.length:rows.filter(r=>r.status===key).length})</div>`).join('');$$('.status-tab').forEach(tab=>tab.onclick=()=>{state.status=tab.dataset.key==='__all'?null:tab.dataset.key;state.page=1;applyFilters(false);renderTabs();});}
function applyFilters(showMessage=true){
  if(!validateDates())return;const orderNos=splitValues($('#purchaseOrderNo').value),skus=splitValues($('#skuInput').value),plans=splitValues($('#planNo').value),batches=splitValues($('#batchNo').value),start=$('#startDate').value,end=$('#endDate').value;
  state.filtered=rows.filter(row=>(!orderNos.length||orderNos.some(v=>[row.ecNo,row.lxNo,row.midNo].some(no=>no.toLowerCase().includes(v))))&&includesAny(row.sku,skus)&&includesAny(row.planNo,plans)&&includesAny(row.batchNo,batches)&&equalsAny(row.supplier,state.suppliers)&&equalsAny(row.warehouse,state.warehouses)&&equalsAny(row.platform,state.platforms)&&equalsAny(row.store,state.stores)&&equalsAny(row.team,state.teams)&&equalsAny(row.receiver,state.receivers)&&equalsAny(row.creator,state.creators)&&(!state.status||row.status===state.status)&&(!start||row.receiveDate>=start)&&(!end||row.receiveDate<=end));
  state.page=Math.min(state.page,Math.max(1,Math.ceil(state.filtered.length/state.pageSize)));renderTable();if(showMessage)toast(`查询完成，共 ${state.filtered.length} 条结果`);
}
const multiConfigs=[['#supplierMulti',suppliers,'suppliers','供应商（可多选）'],['#warehouseMulti',warehouses,'warehouses','采购仓库（可多选）'],['#platformMulti',platforms,'platforms','平台（可多选）'],['#storeMulti',stores,'stores','店铺（可多选）'],['#teamMulti',teams,'teams','团队（可多选）'],['#receiverMulti',receivers,'receivers','收货人（可多选）'],['#creatorMulti',creators,'creators','创建人（可多选）']];
function reset(){
  Object.assign(state,{suppliers:[],warehouses:[],platforms:[],stores:[],teams:[],receivers:[],creators:['Admin'],status:null,page:1,filtered:[...rows]});['#purchaseOrderNo','#skuInput','#planNo','#batchNo','#startDate','#endDate'].forEach(id=>$(id).value='');
  multiConfigs.forEach(([id,,key,placeholder])=>{const root=$(id);root.querySelectorAll('input').forEach(input=>input.checked=state[key].includes(input.value));const trigger=root.querySelector('[data-trigger]');trigger.textContent=state[key].length?state[key].join('、'):placeholder;trigger.classList.toggle('has-value',!!state[key].length);});renderTabs();renderTable();toast('已重置查询条件');
}
function renderTable(){
  const total=state.filtered.length,pages=Math.max(1,Math.ceil(total/state.pageSize)),start=(state.page-1)*state.pageSize,data=state.filtered.slice(start,start+state.pageSize);$('#totalCount').textContent=total;$('#jumpPage').value=state.page;$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=pages;$('#pageButtons').innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${state.page===i+1?'current':''}" data-page="${i+1}">${i+1}</button>`).join('');$$('[data-page]').forEach(button=>button.onclick=()=>{state.page=Number(button.dataset.page);renderTable();});
  if(!data.length){$('#tableBody').innerHTML='<tr class="empty-row"><td colspan="13"><div class="empty-icon">◇</div>暂无符合条件的数据</td></tr>';syncSelection();return;}
  $('#tableBody').innerHTML=data.map(row=>`<tr class="po-group-row"><td><input class="row-check" type="checkbox" data-id="${row.id}" ${state.selected.has(row.id)?'checked':''}></td><td colspan="12"><span class="group-arrow">⌄</span><b>采购单号（易仓）：${row.ecNo}</b>（${row.status}）<span class="sync-icon">↻</span><a>采购跟踪号：${row.trackingNo}</a><span>领星采购单号：${row.lxNo}</span><span>采购数：${row.purchaseQty}</span><span>在途数：${row.transitQty}</span><span>到货数：${row.arrivedQty}</span><span>采购金额：${row.amount}</span><span>税率：${row.tax}%</span><span>供应商：${row.supplier}</span></td></tr><tr class="po-detail-row"><td><input class="row-check" type="checkbox" data-id="${row.id}" ${state.selected.has(row.id)?'checked':''}></td><td>${row.midNo}-1</td><td>${row.planNo}</td><td class="left"><span class="thumb">${row.icon}</span>${row.sku}</td><td>${row.purchaseQty} pcs</td><td>${row.transitQty} pcs</td><td>${row.arrivedQty} pcs</td><td>${row.pendingQty} pcs</td><td>${row.receiveQty} pcs</td><td>–</td><td>${row.materialFee}</td><td>${row.freight}</td><td>${row.otherFee}</td></tr>`).join('');$$('.row-check').forEach(check=>check.onchange=()=>{const id=Number(check.dataset.id);check.checked?state.selected.add(id):state.selected.delete(id);$$(`.row-check[data-id="${id}"]`).forEach(box=>box.checked=check.checked);syncSelection();});syncSelection();
}
function syncSelection(){const visible=$$('.row-check'),checked=visible.filter(x=>x.checked).length;$('#selectedCount').textContent=state.selected.size;$('#selectAll').checked=visible.length>0&&checked===visible.length;$('#selectAll').indeterminate=checked>0&&checked<visible.length;}
$('#selectAll').onchange=e=>{$$('.row-check').forEach(check=>{check.checked=e.target.checked;const id=Number(check.dataset.id);e.target.checked?state.selected.add(id):state.selected.delete(id);});syncSelection();};$('#searchBtn').onclick=()=>{state.page=1;applyFilters();};$('#resetBtn').onclick=reset;$('#refreshBtn').onclick=()=>{applyFilters(false);toast('数据已刷新');};$('#pageSize').onchange=e=>{state.pageSize=Number(e.target.value);state.page=1;renderTable();};$('#prevPage').onclick=()=>{if(state.page>1){state.page--;renderTable();}};$('#nextPage').onclick=()=>{const pages=Math.ceil(state.filtered.length/state.pageSize);if(state.page<pages){state.page++;renderTable();}};$('#jumpPage').onchange=e=>{const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(pages,Math.max(1,Number(e.target.value)||1));renderTable();};
$$('#purchaseOrderNo,#skuInput,#planNo,#batchNo').forEach(input=>input.addEventListener('keydown',e=>{if(e.key==='Enter')$('#searchBtn').click();}));$$('#startDate,#endDate').forEach(input=>input.addEventListener('click',()=>{if(typeof input.showPicker==='function'){try{input.showPicker();}catch{}}}));
function initQueryExpand(){const panel=$('.query-panel'),button=$('#queryExpand'),arrow=button.querySelector('.query-arrow'),label=button.querySelector('.query-expand-text');button.onclick=()=>{const expanded=panel.classList.toggle('expanded');arrow.textContent=expanded?'⌃':'⌄';label.textContent=expanded?'收起':'展开';button.setAttribute('aria-expanded',String(expanded));};}
function initPageNav(){$$('[data-page-nav]').forEach(item=>item.onclick=()=>{const page=item.dataset.pageNav;if(window.parent!==window)window.parent.postMessage({type:'prototype:navigate',page},'*');else window.location.href={stock:'../stock-plan/index.html',purchase:'../purchase-plan/index.html',shipment:'../shipment-plan/index.html',purchaseOrder:'../purchase-orders/index.html'}[page];});}
function initResponsiveQueryLayout(){
  const panel=$('.query-panel'),rowOne=$('#queryRowOne'),rowTwo=$('#queryRowTwo'),advanced=$('.advanced-query-row'),actions=$('.query-actions'),items=$$('.query-item[data-query-order]').sort((a,b)=>Number(a.dataset.queryOrder)-Number(b.dataset.queryOrder));
  const itemWidth=item=>{if(item.classList.contains('time-query'))return [...item.children].reduce((sum,child)=>sum+(child.getBoundingClientRect().width||parseFloat(getComputedStyle(child).width)||0),0)+10;const child=item.firstElementChild;return child.getBoundingClientRect().width||parseFloat(getComputedStyle(child).width)||0;};
  const layout=()=>{const expanded=panel.classList.contains('expanded');items.forEach(item=>rowOne.appendChild(item));rowTwo.appendChild(actions);const available=panel.clientWidth-28,gap=10,actionWidth=actions.getBoundingClientRect().width+gap;let row=1,usedOne=0,usedTwo=actionWidth;items.forEach(item=>{const width=itemWidth(item),needed=width+((row===1&&usedOne)||(row===2&&usedTwo>actionWidth)?gap:0);if(row===1&&usedOne+needed<=available){rowOne.appendChild(item);usedOne+=needed;return;}row=2;const secondNeeded=width+(usedTwo>actionWidth?gap:0);if(usedTwo+secondNeeded<=available){rowTwo.insertBefore(item,actions);usedTwo+=secondNeeded;return;}advanced.appendChild(item);});const hasAdvanced=advanced.querySelector('.query-item');$('#queryExpand').hidden=!hasAdvanced;if(!hasAdvanced&&expanded){panel.classList.remove('expanded');$('#queryExpand .query-arrow').textContent='⌄';$('#queryExpand .query-expand-text').textContent='展开';}};layout();let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(layout,80);});
}
const ownershipSkuPool=[
  {sku:'140US260008',sellerSku:'ARC-WELDER-140',asin:'B0D140US26',platform:'Amazon',store:'Amazon US 旗舰店',availableQty:9},
  {sku:'42101000004',sellerSku:'ARC-MASK-004',asin:'B0C421MASK4',platform:'Amazon',store:'ARCCAP',availableQty:66},
  {sku:'XX123456-1',sellerSku:'EB-WIRE-01',asin:'B0BXX12345',platform:'eBay',store:'arccaptain',availableQty:100},
  {sku:'DD123456',sellerSku:'B2C-GLOVE-DD',asin:'B09DD12345',platform:'B2C',store:'Lowes_ar',availableQty:28},
  {sku:'EE123456',sellerSku:'AMZ-HELMET-EE',asin:'B08EE12345',platform:'Amazon',store:'Amazon US 旗舰店',availableQty:110},
  {sku:'FF123456',sellerSku:'OFFLINE-FF123',asin:'B07FF12345',platform:'线下订单',store:'线下订单',availableQty:36}
];
const ownershipStores={Amazon:['ARCCAP','Amazon US 旗舰店'],eBay:['arccaptain'],B2C:['Lowes_ar'],线下订单:['线下订单']};
const ownership={context:null,results:[],details:[],errors:{},submitting:false};
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function ownershipOptions(values,current,placeholder){return `<option value="">${placeholder}</option>`+values.map(value=>`<option value="${escapeHtml(value)}" ${value===current?'selected':''}>${escapeHtml(value)}</option>`).join('');}
function setOwnershipStores(select,platform,current=''){const values=ownershipStores[platform]||[];select.innerHTML=ownershipOptions(values,values.includes(current)?current:'','调入店铺');select.disabled=!platform;}
function ownershipHasContent(){return !!$('#ownershipKeywords').value.trim()||ownership.details.length>0||!!$('#batchPlatform').value||!!$('#batchStore').value;}
function resetOwnership(){ownership.results=[];ownership.details=[];ownership.errors={};ownership.submitting=false;$('#ownershipKeywords').value='';$('#ownershipSearchHint').textContent='请输入关键词后搜索';$('#ownershipSearchHint').className='ownership-hint';$('#ownershipError').textContent='';$('#batchPlatform').value='';setOwnershipStores($('#batchStore'),'');renderOwnershipResults();renderOwnershipDetails();}
function rowToOwnershipSku(row){const mock=ownershipSkuPool.find(item=>item.sku===row.sku);return mock||{sku:row.sku,sellerSku:`${row.sku}-SELLER`,asin:`B0${String(row.id).padStart(8,'0')}`,platform:row.platform,store:row.store,availableQty:Math.max(1,row.transitQty||row.purchaseQty)};}
function openOwnership(){
  resetOwnership();const selectedRows=rows.filter(row=>state.selected.has(row.id));const contextRow=selectedRows[0]||state.filtered[0]||rows[0];ownership.context=contextRow;$('#ownershipPoNo').textContent=contextRow.ecNo;$('#ownershipStatus').textContent=contextRow.status;$('#ownershipTransit').textContent=`${contextRow.transitQty} pcs`;
  selectedRows.forEach(row=>addOwnershipDetail(rowToOwnershipSku(row),false));renderOwnershipDetails();const modal=$('#ownershipModal');modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('#ownershipKeywords').focus(),0);
}
function closeOwnership(force=false){if(!force&&ownershipHasContent()){showOwnershipConfirm('放弃未保存内容？','当前填写内容不会保存，确认关闭吗？','确认关闭',()=>closeOwnership(true));return;}const modal=$('#ownershipModal');modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';resetOwnership();}
function showOwnershipConfirm(title,content,confirmText,onConfirm){const modal=$('#ownershipModal');modal.classList.add('confirming');const box=document.createElement('div');box.className='ownership-confirm';box.innerHTML=`<h3>${escapeHtml(title)}</h3><div>${content}</div><div class="ownership-confirm-actions"><button class="btn" data-confirm-cancel>取消</button><button class="btn primary" data-confirm-ok>${escapeHtml(confirmText)}</button></div>`;modal.appendChild(box);const remove=()=>{box.remove();modal.classList.remove('confirming');};box.querySelector('[data-confirm-cancel]').onclick=remove;box.querySelector('[data-confirm-ok]').onclick=()=>{remove();onConfirm();};}
function parseOwnershipKeywords(value){return [...new Set(value.split(/[\s,，;；]+/).map(item=>item.trim()).filter(Boolean).map(item=>item.toLowerCase()))];}
function searchOwnership(){const keywords=parseOwnershipKeywords($('#ownershipKeywords').value),hint=$('#ownershipSearchHint');hint.className='ownership-hint';if(!keywords.length){ownership.results=[];hint.textContent='请输入 SKU、SellerSKU 或 ASIN';hint.classList.add('error');renderOwnershipResults();return;}const matchedKeys=new Set();ownership.results=ownershipSkuPool.filter(item=>keywords.some(key=>{const matched=[item.sku,item.sellerSku,item.asin].some(value=>value.toLowerCase()===key);if(matched)matchedKeys.add(key);return matched;}));const unmatched=keywords.filter(key=>!matchedKeys.has(key));if(!ownership.results.length){hint.textContent='未找到匹配 SKU，请检查关键词';hint.classList.add('error');}else if(unmatched.length){hint.textContent=`共 ${keywords.length} 个关键词，${unmatched.length} 个未匹配：${unmatched.join('、')}`;hint.classList.add('warning');}else hint.textContent=`已匹配 ${ownership.results.length} 个 SKU`;
  renderOwnershipResults();
}
function addOwnershipDetail(item,notify=true){if(ownership.details.some(detail=>detail.sku===item.sku)){if(notify)toast(`${item.sku} 已在调整明细中，未重复加入`,'error');return;}ownership.details.push({...item,targetPlatform:'',targetStore:'',targetSku:item.sellerSku||item.asin,qty:'',errors:{}});renderOwnershipDetails();}
function removeOwnershipDetail(sku){ownership.details=ownership.details.filter(item=>item.sku!==sku);renderOwnershipResults();renderOwnershipDetails();}
function renderOwnershipResults(){const root=$('#ownershipResults');if(!ownership.results.length){root.innerHTML='<div class="ownership-empty">暂无搜索结果</div>';return;}const allChecked=ownership.results.every(item=>ownership.details.some(detail=>detail.sku===item.sku));root.innerHTML=`<table class="ownership-table"><thead><tr><th class="check-cell"><input id="ownershipCheckAll" type="checkbox" ${allChecked?'checked':''}></th><th>SKU / SellerSKU / ASIN</th><th>当前平台 / 店铺</th><th class="qty-cell">可调整数量</th></tr></thead><tbody>${ownership.results.map(item=>`<tr><td class="check-cell"><input class="ownership-result-check" type="checkbox" data-sku="${escapeHtml(item.sku)}" ${ownership.details.some(detail=>detail.sku===item.sku)?'checked':''}></td><td><b>${escapeHtml(item.sku)}</b><div class="source-info">${escapeHtml(item.sellerSku)} / ${escapeHtml(item.asin)}</div></td><td>${escapeHtml(item.platform)}<div class="source-info">${escapeHtml(item.store)}</div></td><td class="qty-cell">${item.availableQty}</td></tr>`).join('')}</tbody></table>`;
  $('#ownershipCheckAll').onchange=e=>{ownership.results.forEach(item=>{if(e.target.checked)addOwnershipDetail(item,false);else removeOwnershipDetail(item.sku);});renderOwnershipResults();renderOwnershipDetails();};$$('.ownership-result-check').forEach(check=>check.onchange=()=>{const item=ownership.results.find(result=>result.sku===check.dataset.sku);check.checked?addOwnershipDetail(item):removeOwnershipDetail(item.sku);renderOwnershipResults();});
}
function validateOwnershipDetail(detail){const errors={};if(!detail.targetPlatform)errors.targetPlatform='请选择调入平台';if(!detail.targetStore)errors.targetStore='请选择调入店铺';else if(detail.targetPlatform&&!(ownershipStores[detail.targetPlatform]||[]).includes(detail.targetStore))errors.targetStore='店铺不属于所选平台';if(!detail.targetSku.trim())errors.targetSku='请输入目标 SellerSKU/ASIN';if(!detail.qty)errors.qty='请输入调入数量';else if(!/^[1-9]\d*$/.test(String(detail.qty)))errors.qty='数量须为正整数';else if(Number(detail.qty)>detail.availableQty)errors.qty=`不能超过 ${detail.availableQty}`;detail.errors=errors;return !Object.keys(errors).length;}
function renderOwnershipDetails(){const root=$('#ownershipDetails');$('#detailCount').textContent=`（${ownership.details.length} 个 SKU）`;if(!ownership.details.length)root.innerHTML='<div class="ownership-empty">请先搜索并勾选需要调整的 SKU</div>';else root.innerHTML=`<table class="ownership-table"><thead><tr><th style="width:205px">原 SKU 信息</th><th style="width:85px">可调整</th><th style="width:145px">调入平台</th><th style="width:155px">调入店铺</th><th style="width:190px">目标 SellerSKU/ASIN</th><th style="width:120px">调入数量</th><th class="action-cell">操作</th></tr></thead><tbody>${ownership.details.map(item=>`<tr data-detail="${escapeHtml(item.sku)}"><td><b>${escapeHtml(item.sku)}</b><div class="source-info">${escapeHtml(item.sellerSku)} / ${escapeHtml(item.asin)}<br>${escapeHtml(item.platform)} / ${escapeHtml(item.store)}</div></td><td>${item.availableQty}</td><td><select class="ownership-field ${item.errors.targetPlatform?'invalid':''}" data-field="targetPlatform">${ownershipOptions(Object.keys(ownershipStores),item.targetPlatform,'请选择')}</select><div class="field-error">${escapeHtml(item.errors.targetPlatform||'')}</div></td><td><select class="ownership-field ${item.errors.targetStore?'invalid':''}" data-field="targetStore" ${item.targetPlatform?'':'disabled'}>${ownershipOptions(ownershipStores[item.targetPlatform]||[],item.targetStore,'请选择')}</select><div class="field-error">${escapeHtml(item.errors.targetStore||'')}</div></td><td><input class="ownership-field ${item.errors.targetSku?'invalid':''}" data-field="targetSku" value="${escapeHtml(item.targetSku)}"><div class="field-error">${escapeHtml(item.errors.targetSku||'')}</div></td><td><input class="ownership-field ${item.errors.qty?'invalid':''}" data-field="qty" inputmode="numeric" value="${escapeHtml(item.qty)}"><div class="field-error">${escapeHtml(item.errors.qty||'')}</div></td><td class="action-cell"><button class="delete-detail" type="button">删除</button></td></tr>`).join('')}</tbody></table>`;
  root.querySelectorAll('[data-detail]').forEach(row=>{const detail=ownership.details.find(item=>item.sku===row.dataset.detail);row.querySelector('.delete-detail').onclick=()=>removeOwnershipDetail(detail.sku);row.querySelectorAll('[data-field]').forEach(field=>field.onchange=()=>{const key=field.dataset.field;detail[key]=field.value;if(key==='targetPlatform'&&!(ownershipStores[field.value]||[]).includes(detail.targetStore))detail.targetStore='';validateOwnershipDetail(detail);renderOwnershipDetails();});});updateOwnershipSummary();
}
function updateOwnershipSummary(){const total=ownership.details.reduce((sum,item)=>sum+(/^[1-9]\d*$/.test(String(item.qty))?Number(item.qty):0),0);$('#ownershipSelectedCount').textContent=ownership.details.length;$('#ownershipTotalQty').textContent=total;const disabled=!ownership.details.length;$('#batchPlatform').disabled=disabled;$('#batchStore').disabled=disabled||!$('#batchPlatform').value;$('#applyBatch').disabled=disabled;$('#clearDetails').disabled=disabled;}
function validateOwnership(){if(!ownership.details.length){$('#ownershipError').textContent='请至少选择 1 个 SKU';return false;}const valid=ownership.details.map(validateOwnershipDetail).every(Boolean);$('#ownershipError').textContent=valid?'':'请完善明细中的必填信息和调入数量';renderOwnershipDetails();if(!valid){const invalid=$('.ownership-field.invalid');if(invalid)invalid.focus();}return valid;}
function submitOwnership(){if(ownership.submitting||!validateOwnership())return;const total=ownership.details.reduce((sum,item)=>sum+Number(item.qty),0);showOwnershipConfirm('确认提交货权调整？',`<p>采购单号：<b>${escapeHtml(ownership.context.ecNo)}</b></p><p>SKU 行数：<b>${ownership.details.length}</b></p><p>数量合计：<b>${total}</b></p><p>提交后将调整采购单在途货权。</p>`,'确认提交',()=>{ownership.submitting=true;const button=$('#ownershipSubmit');button.disabled=true;button.textContent='提交中...';setTimeout(()=>{ownership.submitting=false;button.disabled=false;button.textContent='提交调整';closeOwnership(true);toast('货权调整提交成功，采购单数据已刷新');$('#tableArea').classList.add('ownership-refresh');setTimeout(()=>$('#tableArea').classList.remove('ownership-refresh'),1000);},900);});}
function initOwnership(){const platform=$('#batchPlatform'),store=$('#batchStore');platform.innerHTML=ownershipOptions(Object.keys(ownershipStores),'','调入平台');platform.onchange=()=>setOwnershipStores(store,platform.value);$('#applyBatch').onclick=()=>{if(!ownership.details.length)return;if(!platform.value||!store.value){$('#ownershipError').textContent='请先选择调入平台和调入店铺';return;}ownership.details.forEach(item=>{item.targetPlatform=platform.value;item.targetStore=store.value;validateOwnershipDetail(item);});$('#ownershipError').textContent='';renderOwnershipDetails();toast(`已应用到 ${ownership.details.length} 个 SKU`);};$('#ownershipSearch').onclick=searchOwnership;$('#ownershipClearSearch').onclick=()=>{$('#ownershipKeywords').value='';ownership.results=[];$('#ownershipSearchHint').textContent='已清空搜索，调整明细保留';$('#ownershipSearchHint').className='ownership-hint';renderOwnershipResults();};$('#clearDetails').onclick=()=>{ownership.details=[];renderOwnershipResults();renderOwnershipDetails();};$('#openOwnershipTop').onclick=openOwnership;$('#openOwnershipBottom').onclick=openOwnership;$('#ownershipClose').onclick=()=>closeOwnership();$('#ownershipCancel').onclick=()=>closeOwnership();$('#ownershipSubmit').onclick=submitOwnership;$('#ownershipModal').onclick=e=>{if(e.target===$('#ownershipModal'))closeOwnership();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#ownershipModal').classList.contains('show')&&!$('#ownershipModal').classList.contains('confirming'))closeOwnership();});}
initPageNav();initQueryExpand();multiConfigs.forEach(config=>initMulti(...config));initResponsiveQueryLayout();renderTabs();renderTable();initOwnership();
