const suppliers=['JASIC 供应商','ARCCAP 供应商','华南五金','东莞焊材','测试供应商'];
const warehouses=['东莞采购仓','深圳采购仓','宁波采购仓','洛杉矶海外仓','供应商直发仓'];
const platforms=['Amazon','eBay','B2C','线下订单'];
const stores=['ARCCAP','Lowes_ar','arccaptain','Amazon US 旗舰店','线下订单'];
const teams=['亚马逊团队','Jasic团队','eBay团队','B端团队','公共库存'];
const receivers=['张敏','李晨','王磊','赵倩','仓库管理员'];
const creators=['Admin','张敏','李晨','王磊','系统管理员'];
const statusPool=[...Array(7).fill('待提交'),...Array(10).fill('待收货'),...Array(10).fill('已完成')];
const skuPool=['140US260008','42101000004','XX123456-1','DD123456','EE123456','FF123456','KK123456','fan-test-sku'];
const icons=['🎒','🧰','▧','📦','🧯','🪖','🌺','🐹'];

const rows=Array.from({length:27},(_,i)=>({
  id:i+1,ecNo:`ECPO2026${String(805001+i)}`,lxNo:`LXPO2026${String(610001+i)}`,midNo:`PO2026${String(727001+i)}`,
  sku:skuPool[i%skuPool.length],icon:icons[i%icons.length],supplier:suppliers[i%suppliers.length],planNo:`CGJH202608${String(1001+i)}`,batchNo:`PC2026${String(8001+i)}`,
  warehouse:warehouses[i%warehouses.length],platform:platforms[i%platforms.length],store:stores[i%stores.length],team:teams[i%teams.length],receiver:receivers[i%receivers.length],creator:creators[i%creators.length],
  receiveDate:`2026-08-${String(6+(i%22)).padStart(2,'0')}`,status:statusPool[i],amount:`¥ ${(90+i*1376).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`,
  purchaseQty:[9,66,100,2000,110][i%5],transitQty:[0,66,100,2000,110][i%5],arrivedQty:i%4===0?9:i%4===1?0:i%4===2?0:210,pendingQty:i%3===0?0:i%3===1?2000:11,receiveQty:i%4===0?8:0,
  trackingNo:`PO2026${String(805001+i)}`,tax:[0,88,5,0][i%4],materialFee:i%5===0?'¥ 100.00':'¥ 0.00',freight:i%5===0?'¥ 10.00':'¥ 0.00',otherFee:'¥ 0.00'
}));

const statusDefs=[['全部',null],['待提交','待提交'],['待审批','待审批'],['待收货','待收货'],['已完成','已完成']];
const state={suppliers:[],warehouses:[],platforms:[],stores:[],teams:[],receivers:[],creators:['Admin'],status:null,page:1,pageSize:25,selected:new Set(),filtered:[...rows]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(text,type='success'){const el=$('#toast');el.textContent=text;el.classList.toggle('error',type==='error');el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800);}
function closeMenus(except){$$('.multi').forEach(m=>{if(m!==except){m.querySelector('[data-menu]').classList.remove('show');m.querySelector('[data-trigger]').classList.remove('open');}});}
document.addEventListener('click',()=>closeMenus());
function initMulti(rootId,items,key,placeholder){
  const root=$(rootId),trigger=root.querySelector('[data-trigger]'),menu=root.querySelector('[data-menu]');
  const sync=()=>{state[key]=[...menu.querySelectorAll('input:checked')].map(x=>x.value);trigger.textContent=state[key].length?`${state[key].slice(0,2).join('、')}${state[key].length>2?` +${state[key].length-2}`:''}`:placeholder;trigger.classList.toggle('has-value',!!state[key].length);};
  menu.innerHTML=items.map(v=>`<label><input type="checkbox" value="${v}" ${state[key].includes(v)?'checked':''}>${v}</label>`).join('');trigger.onclick=e=>{e.stopPropagation();closeMenus(root);menu.classList.toggle('show');trigger.classList.toggle('open',menu.classList.contains('show'));};menu.onclick=e=>e.stopPropagation();menu.onchange=sync;sync();
}
function splitValues(value){return [...new Set(value.trim().toLowerCase().split(/[\s,，;；]+/).filter(Boolean))];}
function includesAny(value,values){return !values.length||values.some(v=>(value||'').toLowerCase().includes(v));}
function equalsAny(value,values){return !values.length||values.includes(value);}
function validateDates(){const start=$('#startDate').value,end=$('#endDate').value;if((start&&!end)||(!start&&end)){toast('请选择完整的收货时间范围','error');return false;}if(start&&end&&start>end){toast('开始日期不能晚于结束日期','error');return false;}return true;}
function renderTabs(){$('#statusTabs').innerHTML='<span class="tab-check">☑</span>'+statusDefs.map(([label,key])=>`<div class="status-tab ${state.status===key?'active':''}" data-key="${key===null?'__all':key}">${label}(${key===null?rows.length:rows.filter(r=>r.status===key).length})</div>`).join('');$$('.status-tab').forEach(tab=>tab.onclick=()=>{state.status=tab.dataset.key==='__all'?null:tab.dataset.key;state.page=1;applyFilters(false);renderTabs();});}
function applyFilters(showMessage=true){
  if(!validateDates())return;const orderNos=splitValues($('#purchaseOrderNo').value),skus=splitValues($('#skuInput').value),plans=splitValues($('#planNo').value),batches=splitValues($('#batchNo').value),start=$('#startDate').value,end=$('#endDate').value;
  state.filtered=rows.filter(row=>(!orderNos.length||orderNos.some(v=>[row.ecNo,row.lxNo,row.midNo].some(no=>no.toLowerCase().includes(v))))&&includesAny(row.sku,skus)&&includesAny(row.planNo,plans)&&includesAny(row.batchNo,batches)&&equalsAny(row.supplier,state.suppliers)&&equalsAny(row.warehouse,state.warehouses)&&equalsAny(row.platform,state.platforms)&&equalsAny(row.store,state.stores)&&equalsAny(row.team,state.teams)&&equalsAny(row.receiver,state.receivers)&&equalsAny(row.creator,state.creators)&&(!state.status||row.status===state.status)&&(!start||row.receiveDate>=start)&&(!end||row.receiveDate<=end));
  state.page=Math.min(state.page,Math.max(1,Math.ceil(state.filtered.length/state.pageSize)));renderTable();if(showMessage)toast(`查询完成，共 ${state.filtered.length} 条结果`);
}
const multiConfigs=[['#supplierMulti',suppliers,'suppliers','供应商（可多选）'],['#warehouseMulti',warehouses,'warehouses','采购仓库（可多选）'],['#platformMulti',platforms,'platforms','平台（可多选）'],['#storeMulti',stores,'stores','店铺（可多选）'],['#teamMulti',teams,'teams','团队（可多选）'],['#receiverMulti',receivers,'receivers','收货人（可多选）'],['#creatorMulti',creators,'creators','创建人（可多选）']];
function reset(){
  Object.assign(state,{suppliers:[],warehouses:[],platforms:[],stores:[],teams:[],receivers:[],creators:['Admin'],status:null,page:1,filtered:[...rows]});['#purchaseOrderNo','#skuInput','#planNo','#batchNo','#startDate','#endDate'].forEach(id=>$(id).value='');
  multiConfigs.forEach(([id,,key,placeholder])=>{const root=$(id);root.querySelectorAll('input').forEach(input=>input.checked=state[key].includes(input.value));const trigger=root.querySelector('[data-trigger]');trigger.textContent=state[key].length?state[key].join('、'):placeholder;trigger.classList.toggle('has-value',!!state[key].length);});renderTabs();renderTable();toast('已重置查询条件');
}
function renderTable(){
  const total=state.filtered.length,pages=Math.max(1,Math.ceil(total/state.pageSize)),start=(state.page-1)*state.pageSize,data=state.filtered.slice(start,start+state.pageSize);$('#totalCount').textContent=total;$('#jumpPage').value=state.page;$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=pages;$('#pageButtons').innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${state.page===i+1?'current':''}" data-page="${i+1}">${i+1}</button>`).join('');$$('[data-page]').forEach(button=>button.onclick=()=>{state.page=Number(button.dataset.page);renderTable();});
  if(!data.length){$('#tableBody').innerHTML='<tr class="empty-row"><td colspan="13"><div class="empty-icon">◇</div>暂无符合条件的数据</td></tr>';syncSelection();return;}
  $('#tableBody').innerHTML=data.map(row=>`<tr class="po-group-row"><td><input class="row-check" type="checkbox" data-id="${row.id}" ${state.selected.has(row.id)?'checked':''}></td><td colspan="12"><span class="group-arrow">⌄</span><b>采购单号（易仓）：${row.ecNo}</b>（${row.status}）<span class="sync-icon">↻</span><a>采购跟踪号：${row.trackingNo}</a><span>领星采购单号：${row.lxNo}</span><span>采购数：${row.purchaseQty}</span><span>在途数：${row.transitQty}</span><span>到货数：${row.arrivedQty}</span><span>采购金额：${row.amount}</span><span>税率：${row.tax}%</span><span>供应商：${row.supplier}</span></td></tr><tr class="po-detail-row"><td><input class="row-check" type="checkbox" data-id="${row.id}" ${state.selected.has(row.id)?'checked':''}></td><td>${row.midNo}-1</td><td>${row.planNo}</td><td class="left"><span class="thumb">${row.icon}</span>${row.sku}</td><td>${row.purchaseQty} pcs</td><td>${row.transitQty} pcs</td><td>${row.arrivedQty} pcs</td><td>${row.pendingQty} pcs</td><td>${row.receiveQty} pcs</td><td>–</td><td>${row.materialFee}</td><td>${row.freight}</td><td>${row.otherFee}</td></tr>`).join('');$$('.row-check').forEach(check=>check.onchange=()=>{const id=Number(check.dataset.id);check.checked?state.selected.add(id):state.selected.delete(id);$$(`.row-check[data-id="${id}"]`).forEach(box=>box.checked=check.checked);syncSelection();});syncSelection();
}
function syncSelection(){const visible=$$('.row-check'),checked=visible.filter(x=>x.checked).length;$('#selectedCount').textContent=state.selected.size;$('#selectAll').checked=visible.length>0&&checked===visible.length;$('#selectAll').indeterminate=checked>0&&checked<visible.length;}
$('#selectAll').onchange=e=>{$$('.row-check').forEach(check=>{check.checked=e.target.checked;const id=Number(check.dataset.id);e.target.checked?state.selected.add(id):state.selected.delete(id);});syncSelection();};$('#searchBtn').onclick=()=>{state.page=1;applyFilters();};$('#resetBtn').onclick=reset;$('#refreshBtn').onclick=()=>{applyFilters(false);toast('数据已刷新');};$('#pageSize').onchange=e=>{state.pageSize=Number(e.target.value);state.page=1;renderTable();};$('#prevPage').onclick=()=>{if(state.page>1){state.page--;renderTable();}};$('#nextPage').onclick=()=>{const pages=Math.ceil(state.filtered.length/state.pageSize);if(state.page<pages){state.page++;renderTable();}};$('#jumpPage').onchange=e=>{const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(pages,Math.max(1,Number(e.target.value)||1));renderTable();};
$$('#purchaseOrderNo,#skuInput,#planNo,#batchNo').forEach(input=>input.addEventListener('keydown',e=>{if(e.key==='Enter')$('#searchBtn').click();}));$$('#startDate,#endDate').forEach(input=>input.addEventListener('click',()=>{if(typeof input.showPicker==='function'){try{input.showPicker();}catch{}}}));
function initQueryExpand(){const panel=$('.query-panel'),button=$('#queryExpand'),arrow=button.querySelector('.query-arrow'),label=button.querySelector('.query-expand-text');button.onclick=()=>{const expanded=panel.classList.toggle('expanded');arrow.textContent=expanded?'⌃':'⌄';label.textContent=expanded?'收起':'展开';button.setAttribute('aria-expanded',String(expanded));};}
function initPageNav(){$$('[data-page-nav]').forEach(item=>item.onclick=()=>{const page=item.dataset.pageNav;if(window.parent!==window)window.parent.postMessage({type:'prototype:navigate',page},'*');else window.location.href={stock:'../stock-plan/index.html',purchase:'../purchase-plan/index.html',shipment:'../shipment-plan/index.html',purchaseOrder:'../purchase-orders/index.html'}[page];});}
function initResponsiveQueryLayout(){
  const panel=$('.query-panel'),rowOne=$('#queryRowOne'),rowTwo=$('#queryRowTwo'),advanced=$('.advanced-query-row'),actions=$('.query-actions'),items=$$('.query-item[data-query-order]').sort((a,b)=>Number(a.dataset.queryOrder)-Number(b.dataset.queryOrder));
  const itemWidth=item=>{if(item.classList.contains('time-query'))return [...item.children].reduce((sum,child)=>sum+(child.getBoundingClientRect().width||parseFloat(getComputedStyle(child).width)||0),0)+10;const child=item.firstElementChild;return child.getBoundingClientRect().width||parseFloat(getComputedStyle(child).width)||0;};
  const layout=()=>{const expanded=panel.classList.contains('expanded');items.forEach(item=>rowOne.appendChild(item));rowTwo.appendChild(actions);const available=panel.clientWidth-28,gap=10,actionWidth=actions.getBoundingClientRect().width+gap;let row=1,usedOne=0,usedTwo=actionWidth;items.forEach(item=>{const width=itemWidth(item),needed=width+((row===1&&usedOne)||(row===2&&usedTwo>actionWidth)?gap:0);if(row===1&&usedOne+needed<=available){rowOne.appendChild(item);usedOne+=needed;return;}row=2;const secondNeeded=width+(usedTwo>actionWidth?gap:0);if(usedTwo+secondNeeded<=available){rowTwo.insertBefore(item,actions);usedTwo+=secondNeeded;return;}advanced.appendChild(item);});const hasAdvanced=advanced.querySelector('.query-item');$('#queryExpand').hidden=!hasAdvanced;if(!hasAdvanced&&expanded){panel.classList.remove('expanded');$('#queryExpand .query-arrow').textContent='⌄';$('#queryExpand .query-expand-text').textContent='展开';}};layout();let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(layout,80);});
}
initPageNav();initQueryExpand();multiConfigs.forEach(config=>initMulti(...config));initResponsiveQueryLayout();renderTabs();renderTable();
