    const baseRows=[
      ['CST20260805-1','XX123456-1','测试XX123456-1','','','测试平台','测试店铺','01','测试团队','','','', '待计划确认','Admin','2026-08-05','2026-08-05','2026-08-20','📦'],
      ['JAS20260804-2','42101000004','TIG焊丝-不锈钢/...','10250100710','ARER308L-516','b2c','Lowes_ar...','其他','Jasic团队','100','100','100','已执行','张敏','2026-08-04','2026-08-05','2026-08-18','🧰'],
      ['YMX20260804-2','343010D0002','焊接围裙36寸棕色','10430100114','apron-brown-ca','amazon','ARCCAP...','美国','亚马逊团队','100','100','100','待生成发货计划','李晨','2026-08-04','2026-08-05','2026-08-22','🧥'],
      ['EBA20260804-3','52001000001','大屏焊帽-（黑色）','10400100101','140US160006','ebay','arccaptai...','美国','eBay','100','100','100','已执行','Admin','2026-08-04','2026-08-05','2026-08-25','🥽'],
      ['BDT20260804-1','CC123456','测试组合产品CC','','CC123456-Seller...','b2c','线下订单','01','B端团队','0','0','0','待负责人确认','王磊','2026-08-04','2026-08-05','2026-08-28','🌺'],
      ['CST20260804-1','XX123456','测试XX123456','','','','','01','测试团队...','0','0','0','已作废','Admin','2026-08-04','2026-08-05','2026-08-30',''],
      ['YMX20260804-1','51001010025','小屏焊帽-基础款...','AR-HM-001','Helmet-beiyong05','amazon','ARCCAP...','01','亚马逊团队','10','10','10','待运营确认','张敏','2026-08-04','2026-08-05','2026-08-19','🪖'],
      ['CST20260803-1','510EU000036','小屏焊帽CozyCra...','1040EU03310','','','','EU','测试团队...','0','0','0','已作废','李晨','2026-08-03','2026-08-04','2026-08-23','🎡'],
      ['YMX20260803-2','51001010025','小屏焊帽-基础款...','AR-HM-001','3R-58IR-SEWH','amazon','ARCCAP...','01','亚马逊团队','0','0','0','待计划确认','Admin','2026-08-03','2026-08-04','2026-08-24','🪖'],
      ['YMX20260803-1','51001010025','小屏焊帽-基础款...','AR-HM-001','3R-58IR-SEWH','amazon','ARCCAP...','01','亚马逊团队','0','0','0','待生成发货计划','张敏','2026-08-03','2026-08-04','2026-08-24','🪖'],
      ['BDT20260730-2','BB123456','测试BB123456','','BB123456-Seller...','b2c','线下订单','01','B端团队','0','0','0','已作废','王磊','2026-07-30','2026-08-01','2026-08-20','🌺'],
      ['GGK20260727-4','11301000001','送丝轮K型0.6/0.8','10120100110','','','','01','公共库存','','','','待计划确认','Admin','2026-07-27','2026-08-01','2026-08-18','⚙️'],
      ['YMX20260727-3','51001010025','小屏焊帽-基础款...','AR-HM-001','Helmet-beiyong05','amazon','ARCCAP...','01','亚马逊团队','0','0','0','已执行','李晨','2026-07-27','2026-08-02','2026-08-21','🪖'],
      ['YMX20260727-2','130US160006','ARC130 110V 掌...','10300200306','WELDERARC130...','amazon','ARCCAP...','US','亚马逊团队','100','100','100','待负责人确认','Admin','2026-07-27','2026-08-02','2026-08-25','🧳'],
      ['YMX20260724-8','130US160012','ARC200L 焊机+L...','AR-ARC200R201...','ARC200-LIFTTIG','amazon','ARCCAP...','US','亚马逊团队','100','100','100','待运营确认','张敏','2026-07-24','2026-07-28','2026-08-29','🧳']
    ];
    const remarks=['重点备货，优先确认交期','常规月度备货','新品首批备货计划','海外仓补货，关注安全库存','客户项目专项备货','销量增长补充备货','测试数据，请勿执行','节日促销前置备货'];
    const rows=Array.from({length:32},(_,i)=>{const r=[...baseRows[i%baseRows.length]];if(i>=baseRows.length)r[0]=r[0].replace(/-\d+$/,`-${(i%8)+1}`);const dateKey=r[14].replaceAll('-','');return {id:i+1,plan:r[0],sku:r[1],name:r[2],lx:r[3],seller:r[4],platform:r[5],store:r[6],country:r[7],team:r[8],m8:r[9],m9:r[10],m10:r[11],status:r[12],creator:r[13],created:r[14],updated:r[15],delivery:r[16],icon:r[17],purchaseNo:`PO${dateKey}${String(i+1).padStart(3,'0')}`,planOrderNo:`PLAN${dateKey}${String((i%9)+1).padStart(3,'0')}`,remark:remarks[i%remarks.length]}});
    const statusDefs=[['全部',null],['待计划确认','待计划确认'],['待运营确认','待运营确认'],['待负责人确认','待负责人确认'],['待生成采购计划','待生成采购计划'],['待生成发货计划','待生成发货计划'],['已执行','已执行'],['已作废','已作废']];
    const platforms=['Amazon','eBay','B2C','测试平台'];
    const countries=['美国','中国','英国','日本','US','EU','01','其他'];
    const stores=['ARCCAP','Lowes_ar','arccaptain','线下订单','测试店铺','Amazon US 旗舰店'];
    const teams=['亚马逊团队','Jasic团队','eBay团队','B端团队','公共库存','测试团队'];const creators=['Admin','张敏','李晨','王磊','系统管理员'];
    const state={codes:[],platforms:[],countries:[],stores:[],teams:[],creators:['Admin'],status:null,page:1,pageSize:25,selected:new Set(),filtered:[...rows]};
    const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
    function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1600)}
    function initMulti(rootId,items,key,placeholder){const root=$(rootId),trigger=root.querySelector('[data-trigger]'),menu=root.querySelector('[data-menu]');const sync=()=>{state[key]=[...menu.querySelectorAll('input:checked')].map(x=>x.value);trigger.textContent=state[key].length?`${state[key].slice(0,2).join('、')}${state[key].length>2?` +${state[key].length-2}`:''}`:placeholder;trigger.classList.toggle('has-value',!!state[key].length)};menu.innerHTML=items.map(v=>`<label><input type="checkbox" value="${v}" ${state[key].includes(v)?'checked':''}>${v}</label>`).join('');trigger.onclick=e=>{e.stopPropagation();closeMenus(root);menu.classList.toggle('show');trigger.classList.toggle('open',menu.classList.contains('show'))};menu.onclick=e=>e.stopPropagation();menu.onchange=sync;sync();}
    function closeMenus(except){$$('.multi').forEach(m=>{if(m!==except){m.querySelector('[data-menu]').classList.remove('show');m.querySelector('[data-trigger]').classList.remove('open')}})}document.addEventListener('click',()=>closeMenus());
    function addCode(raw){raw.split(/[\s,，;；]+/).map(v=>v.trim()).filter(Boolean).forEach(v=>{if(!state.codes.includes(v))state.codes.push(v)});renderCodeTags()}
    function renderCodeTags(){const wrap=$('#codeTags');wrap.innerHTML=state.codes.slice(0,2).map((v,i)=>`<span class="chip" title="${v}">${v}<span class="x" data-i="${i}">×</span></span>`).join('')+(state.codes.length>2?`<span class="chip">+${state.codes.length-2}</span>`:'');wrap.querySelectorAll('.x').forEach(x=>x.onclick=e=>{e.stopPropagation();state.codes.splice(Number(x.dataset.i),1);renderCodeTags()})}
    $('#codeInput').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===','){e.preventDefault();addCode(e.target.value);e.target.value=''}});$('#codeInput').addEventListener('paste',e=>{const t=e.clipboardData.getData('text');if(/[\s,，;；]/.test(t)){e.preventDefault();addCode(t)}});$('#codeBox').onclick=()=>$('#codeInput').focus();
    function statusCount(key){return key===null?rows.length:rows.filter(r=>r.status===key).length}
    function renderTabs(){$('#statusTabs').innerHTML=statusDefs.map(([label,key],i)=>`<div class="status-tab ${state.status===key?'active':''}" data-key="${key===null?'__all':key}">${label}(${statusCount(key)})</div>`).join('');$$('.status-tab').forEach(t=>t.onclick=()=>{state.status=t.dataset.key==='__all'?null:t.dataset.key;state.page=1;applyFilters(false);renderTabs()})}
    function dateField(row){return $('#timeType').value==='创建时间'?row.created:$('#timeType').value==='更新时间'?row.updated:row.delivery}
    function splitValues(value){return [...new Set(value.trim().toLowerCase().split(/[\s,，;；]+/).filter(Boolean))]}
    function applyFilters(showMessage=true){const codeType=$('#codeType').value,plans=splitValues($('#planNo').value),purchaseNos=splitValues($('#purchaseNo').value),planOrderNos=splitValues($('#planOrderNo').value),name=$('#productName').value.trim().toLowerCase(),remark=$('#remark').value.trim().toLowerCase(),start=$('#startDate').value,end=$('#endDate').value;state.filtered=rows.filter(r=>{const codeMap={'SKU':r.sku,'领星 SKU':r.lx,'SellerSKU':r.seller,'ASIN':r.seller};const codeOk=!state.codes.length||state.codes.some(c=>(codeMap[codeType]||'').toLowerCase().includes(c.toLowerCase()));const planOk=!plans.length||plans.some(p=>r.plan.toLowerCase().includes(p));const purchaseOk=!purchaseNos.length||purchaseNos.some(p=>r.purchaseNo.toLowerCase().includes(p));const planOrderOk=!planOrderNos.length||planOrderNos.some(p=>r.planOrderNo.toLowerCase().includes(p));const platformOk=!state.platforms.length||state.platforms.some(v=>r.platform.toLowerCase()===v.toLowerCase());const countryOk=!state.countries.length||state.countries.includes(r.country);const storeOk=!state.stores.length||state.stores.some(v=>r.store.toLowerCase().includes(v.toLowerCase()));return codeOk&&planOk&&purchaseOk&&planOrderOk&&(!name||r.name.toLowerCase().includes(name))&&(!remark||r.remark.toLowerCase().includes(remark))&&platformOk&&countryOk&&storeOk&&(!state.teams.length||state.teams.includes(r.team))&&(!state.creators.length||state.creators.includes(r.creator))&&(!state.status||r.status===state.status)&&(!start||dateField(r)>=start)&&(!end||dateField(r)<=end)});state.page=Math.min(state.page,Math.max(1,Math.ceil(state.filtered.length/state.pageSize)));renderTable();if(showMessage)toast(`查询完成，共 ${state.filtered.length} 条结果`)}
    function reset(){state.codes=[];state.platforms=[];state.countries=[];state.stores=[];state.teams=[];state.creators=['Admin'];state.status=null;state.page=1;['#planNo','#productName','#purchaseNo','#planOrderNo','#remark','#startDate','#endDate'].forEach(id=>$(id).value='');$('#codeType').value='SKU';$('#timeType').value='创建时间';$$('.dropdown input').forEach(x=>x.checked=false);const defaults=[['#platformMulti','platforms','平台（可多选）'],['#countryMulti','countries','国家（可多选）'],['#storeMulti','stores','店铺（可多选）'],['#teamMulti','teams','团队（可多选）'],['#creatorMulti','creators','创建人（可多选）']];defaults.forEach(([id,key,p])=>{const root=$(id),menu=root.querySelector('[data-menu]');menu.querySelectorAll('input').forEach(x=>x.checked=state[key].includes(x.value));const t=root.querySelector('[data-trigger]');t.textContent=state[key].length?state[key].join('、'):p;t.classList.toggle('has-value',!!state[key].length)});renderCodeTags();renderTabs();state.filtered=[...rows];renderTable();toast('已重置查询条件')}
    function renderTable(){const total=state.filtered.length,pages=Math.max(1,Math.ceil(total/state.pageSize)),start=(state.page-1)*state.pageSize,data=state.filtered.slice(start,start+state.pageSize);$('#totalCount').textContent=total;$('#jumpPage').value=state.page;$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=pages;$('#pageButtons').innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${state.page===i+1?'current':''}" data-page="${i+1}">${i+1}</button>`).join('');$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.page);renderTable()});if(!data.length){$('#tableBody').innerHTML='<tr class="empty-row"><td colspan="13"><div class="empty-icon">◇</div>暂无符合条件的数据</td></tr>';return}$('#tableBody').innerHTML=data.map(r=>`<tr><td><input class="row-check" type="checkbox" data-id="${r.id}" ${state.selected.has(r.id)?'checked':''}></td><td>${r.plan}</td><td class="left">${r.icon?`<span class="thumb">${r.icon}</span>`:'<span class="no-image">无图</span>'}${r.sku}${r.sku.includes('123456')?'<span class="cube">♧</span>':''}</td><td>${r.name}</td><td>${r.lx}</td><td>${r.seller}</td><td>${r.platform}</td><td>${r.store}</td><td>${r.country}</td><td>${r.team}</td><td>${r.m8}</td><td>${r.m9}</td><td>${r.m10}</td></tr>`).join('');$$('.row-check').forEach(c=>c.onchange=()=>{const id=Number(c.dataset.id);c.checked?state.selected.add(id):state.selected.delete(id);syncSelection()});syncSelection()}
    function syncSelection(){const visible=$$('.row-check'),checked=visible.filter(x=>x.checked).length;$('#selectedCount').textContent=state.selected.size;$('#selectAll').checked=visible.length>0&&checked===visible.length;$('#selectAll').indeterminate=checked>0&&checked<visible.length}
    $('#selectAll').onchange=e=>{$$('.row-check').forEach(c=>{c.checked=e.target.checked;const id=Number(c.dataset.id);e.target.checked?state.selected.add(id):state.selected.delete(id)});syncSelection()};
    $('#searchBtn').onclick=()=>{if($('#codeInput').value.trim()){addCode($('#codeInput').value);$('#codeInput').value=''}state.page=1;applyFilters()};$('#resetBtn').onclick=reset;$('#refreshBtn').onclick=()=>{applyFilters(false);toast('数据已刷新')};$('#pageSize').onchange=e=>{state.pageSize=Number(e.target.value);state.page=1;renderTable()};$('#prevPage').onclick=()=>{if(state.page>1){state.page--;renderTable()}};$('#nextPage').onclick=()=>{const p=Math.ceil(state.filtered.length/state.pageSize);if(state.page<p){state.page++;renderTable()}};$('#jumpPage').onchange=e=>{const p=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(p,Math.max(1,Number(e.target.value)||1));renderTable()};
    $$('#planNo, #productName, #purchaseNo, #planOrderNo, #remark').forEach(input=>input.addEventListener('keydown',e=>{if(e.key==='Enter'){$('#searchBtn').click()}}));
    $$('#startDate, #endDate').forEach(input=>input.addEventListener('click',()=>{if(typeof input.showPicker==='function'){try{input.showPicker()}catch(e){}}}));
    function initQueryExpand(){const panel=$('.query-panel'),button=$('#queryExpand'),arrow=button.querySelector('.query-arrow'),label=button.querySelector('.query-expand-text');button.onclick=()=>{const expanded=panel.classList.toggle('expanded');arrow.textContent=expanded?'⌃':'⌄';label.textContent=expanded?'收起':'展开';button.setAttribute('aria-expanded',String(expanded))}}
    function initPageNav(){$$('[data-page-nav]').forEach(item=>item.onclick=()=>{const page=item.dataset.pageNav;if(window.parent!==window){window.parent.postMessage({type:'prototype:navigate',page},'*')}else{window.location.href={stock:'../stock-plan/index.html',purchase:'../purchase-plan/index.html',shipment:'../shipment-plan/index.html',purchaseOrder:'../purchase-orders/index.html',shipmentOrder:'../shipment-orders/index.html',supplierInventory:'../supplier-inventory/index.html'}[page]}})}
    initPageNav();initQueryExpand();initMulti('#platformMulti',platforms,'platforms','平台（可多选）');initMulti('#countryMulti',countries,'countries','国家（可多选）');initMulti('#storeMulti',stores,'stores','店铺（可多选）');initMulti('#teamMulti',teams,'teams','团队（可多选）');initMulti('#creatorMulti',creators,'creators','创建人（可多选）');renderTabs();renderTable();
